version: '3'
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: erp
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/var/lib/mysql
            - persistent:/var/lib/mysql
    web:
      image: aldorama/django-erp
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000 
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      links:
        - db
volumes:
    persistent: