# Generated by Django 3.2 on 2022-12-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreentidad', models.CharField(max_length=100)),
                ('borrado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Formapago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrefp', models.CharField(max_length=100)),
                ('borrado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprovincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('localidad', models.CharField(max_length=100)),
                ('cuentabancaria', models.CharField(max_length=100)),
                ('codpostal', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('movil', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('borrado', models.CharField(max_length=1)),
                ('codentidad', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.RESTRICT, to='app.entidades')),
                ('codprovincia', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.RESTRICT, to='app.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('localidad', models.CharField(max_length=100)),
                ('cuentabancaria', models.CharField(max_length=100)),
                ('codpostal', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('movil', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('borrado', models.CharField(max_length=1)),
                ('codentidad', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.RESTRICT, to='app.entidades')),
                ('codformapago', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.RESTRICT, to='app.formapago')),
                ('codprovincia', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.RESTRICT, to='app.provincias')),
            ],
        ),
    ]
