# Generated by Django 3.2 on 2022-12-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreentidad', models.CharField(max_length=100)),
                ('borrado', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('borrado', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Formapago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrefp', models.CharField(max_length=100)),
                ('borrado', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('codpostal', models.CharField(max_length=100)),
                ('cuentabancaria', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('movil', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprovincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.persona')),
                ('borrado', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='codprovincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincias'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estructurajuridica', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('codpostal', models.CharField(max_length=100)),
                ('cuentabancaria', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('movil', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('codprovincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.persona')),
                ('borrado', models.CharField(default=0, max_length=1)),
                ('codformapago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formapago')),
            ],
        ),
    ]
