# Generated by Django 3.2 on 2023-01-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio_compra',
            old_name='fecha_fin_servicio',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='servicio_compra',
            old_name='fecha_inicio_servicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='trabajador',
            new_name='contratista',
        ),
        migrations.RemoveField(
            model_name='servicio_compra',
            name='descripcion_compra_servicio',
        ),
        migrations.AlterField(
            model_name='servicio_compra',
            name='fecha_compra',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Orden_compra_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden_servicio', models.DateTimeField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
            ],
        ),
        migrations.AddField(
            model_name='servicio_compra',
            name='orden_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orden_compra_servicio'),
        ),
    ]
