# Generated by Django 3.2 on 2023-01-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja_diaria',
            name='total_compras',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='caja_diaria',
            name='total_ventas',
            field=models.FloatField(default=0, null=True),
        ),
    ]
