# Generated by Django 3.2 on 2023-01-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embajalajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='modificar_ticker',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='precio_ticket',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='proveedor_1',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='proveedor_2',
        ),
        migrations.AddField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.proveedores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulos',
            name='aviso_minimo',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='embalaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.embajalajes'),
        ),
    ]
