# Generated by Django 3.2 on 2023-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision_linea_clie',
            name='remision_hecha',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
