# Generated by Django 3.2 on 2023-01-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embalajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numlinea', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField()),
                ('dcto', models.FloatField()),
                ('totalfactura', models.FloatField()),
                ('fechavencimiento', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='modificar_ticker',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='precio_ticket',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='proveedor_1',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='proveedor_2',
        ),
        migrations.AddField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.proveedores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulos',
            name='aviso_minimo',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3),
        ),
        migrations.CreateModel(
            name='Factura_linea_prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.familia')),
                ('codproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedores')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_linea_clie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('codfamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.familia')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
            ],
        ),
        migrations.AlterField(
            model_name='articulos',
            name='embalaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.embalajes'),
        ),
    ]
