# Generated by Django 3.2 on 2023-01-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_linea_prov',
            name='remision_hecha',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
