# Generated by Django 3.2 on 2023-01-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja_diaria',
            name='fecha',
        ),
        migrations.AddField(
            model_name='caja_diaria',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='caja_diaria',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
