# Generated by Django 3.2 on 2023-01-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidades',
            name='borrado',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='borrado',
        ),
        migrations.RemoveField(
            model_name='formapago',
            name='borrado',
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='borrado',
        ),
        migrations.RemoveField(
            model_name='ubicaciones',
            name='borrado',
        ),
    ]
