# Generated by Django 3.2 on 2023-01-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja_diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('monto_total_inicial', models.FloatField(null=True)),
                ('monto_total_final', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja_tipo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tipo_pago', models.FloatField(null=True)),
                ('caja_diaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.caja_diaria')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compra_prov')),
                ('tipo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.formapago')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.factura_clie')),
            ],
        ),
    ]
