# Generated by Django 3.2 on 2023-01-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_linea_prov',
            name='dsctoproducto',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
