# Generated by Django 3.2 on 2023-01-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_linea_clie',
            name='codproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
