# Generated by Django 3.2 on 2023-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='tipo',
            field=models.CharField(choices=[('Materia Prima', 'Materia Prima'), ('Insumo', 'Insumo'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=50),
        ),
    ]
