# Generated by Django 3.2 on 2023-01-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numlinea', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField()),
                ('dcto', models.FloatField()),
                ('totalfactura', models.FloatField()),
                ('fechavencimiento', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura_linea_prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.familia')),
                ('codproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedores')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_linea_clie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('codfamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.familia')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
            ],
        ),
    ]
