# Generated by Django 3.2 on 2023-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='importe',
        ),
        migrations.AddField(
            model_name='factura_linea_clie',
            name='importe',
            field=models.FloatField(null=True),
        ),
    ]
