# Generated by Django 3.2 on 2023-01-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remision_linea_clie_remision_hecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision_linea_clie',
            name='remision_hecha',
        ),
        migrations.AddField(
            model_name='factura_linea_clie',
            name='remision_hecha',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
