# Generated by Django 3.2 on 2023-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230123_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='estdo_produccion',
            field=models.CharField(choices=[('No Iniciado', 'Iniciado'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Saliendo', 'Saliendo')], default='No Iniciado', max_length=100),
        ),
    ]
