# Generated by Django 3.2 on 2023-01-16 15:00

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230113_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra_prov',
            fields=[
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.factura')),
                ('imagen_factura_compra', models.ImageField(null=True, upload_to=app.models.upload_path2)),
                ('codprov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_linea_prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField(null=True)),
                ('dsctoproducto', models.FloatField()),
                ('codproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.articulos')),
                ('compra_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compra_prov')),
            ],
        ),
    ]
