# Generated by Django 3.2 on 2023-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articulos_impuestos_ubicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ruc',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='ruc',
            field=models.CharField(default='478568437', max_length=100),
            preserve_default=False,
        ),
    ]
