# Generated by Django 3.2 on 2023-01-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230111_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='totalfactura',
            field=models.FloatField(default=0, null=True),
        ),
    ]
