# Generated by Django 3.2 on 2023-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_compra_linea_prov_dsctoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_prov',
            name='detaller_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra_prov',
            name='recibido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
