# Generated by Django 3.2 on 2023-01-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_factura_factura_linea_clie_factura_linea_prov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albaran_linea_clie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionproducto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura_clie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('dsctoproducto', models.FloatField()),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='dcto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='factura_linea_clie',
            name='codcliente',
        ),
        migrations.RemoveField(
            model_name='factura_linea_clie',
            name='codfamilia',
        ),
        migrations.AddField(
            model_name='factura_linea_clie',
            name='codproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.articulos'),
        ),
        migrations.DeleteModel(
            name='Factura_linea_prov',
        ),
        migrations.AddField(
            model_name='albaran_linea_clie',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura_linea_clie'),
        ),
        migrations.AddField(
            model_name='factura_linea_clie',
            name='factura_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.factura_clie'),
        ),
    ]
