# Generated by Django 3.2 on 2023-01-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_compra_linea_prov_remision_hecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(auto_now_add=True)),
                ('estdo_produccion', models.CharField(choices=[('------', '-----'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Saliendo', 'Saliendo')], default='------', max_length=100)),
                ('factura_clie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.factura_clie')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion_linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estdo_produccion_prod', models.CharField(choices=[('------', '-----'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Saliendo', 'Saliendo')], default='------', max_length=100)),
                ('cod_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.factura_linea_clie')),
                ('produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.produccion')),
            ],
        ),
    ]
