# Generated by Django 3.2 on 2023-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_factura_linea_clie_codproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_clie',
            name='contador_productos',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
