# Generated by Django 3.2 on 2023-01-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_caja_diaria_caja_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja_tipo_pago',
            name='caja_diaria',
        ),
        migrations.RemoveField(
            model_name='caja_tipo_pago',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='caja_tipo_pago',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='caja_tipo_pago',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Caja_diaria',
        ),
        migrations.DeleteModel(
            name='Caja_tipo_pago',
        ),
    ]
