# Generated by Django 3.2 on 2023-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230123_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_compra',
            name='precio_compra',
            field=models.FloatField(null=True),
        ),
    ]
