# Generated by Django 3.2 on 2023-01-20 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_precio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision_clie',
            name='fecha_remision',
            field=models.DateField(default=datetime.datetime(2023, 1, 20, 17, 39, 11, 671920, tzinfo=utc)),
        ),
    ]
