# Generated by Django 3.2 on 2023-01-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articulos_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_factura',
            fields=[
                ('factura_servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.factura')),
                ('fecha_pedido', models.DateTimeField(null=True)),
                ('fecha_inicio_servicio', models.DateTimeField(null=True)),
                ('fecha_fin_servicio', models.DateTimeField(null=True)),
                ('costo_total', models.FloatField()),
                ('descripcion_servicio', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicios')),
            ],
        ),
    ]
