# Generated by Django 3.2 on 2023-01-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230111_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Embajalajes',
            new_name='Embalajes',
        ),
    ]
