# Generated by Django 3.2 on 2023-01-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_servicio_compra_precio_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibir_orden_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField()),
                ('costo_total', models.FloatField()),
                ('servicio_compra_referencia', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.servicio_compra')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio_factura',
        ),
    ]
