# Generated by Django 3.2 on 2023-01-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230118_1434'),
        ('app', '0003_auto_20230118_1757'),
    ]

    operations = [
    ]
