# Generated by Django 3.2 on 2023-01-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_servicio_factura_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio_factura',
            name='descripcion_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio_factura',
            name='fecha_fin_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio_factura',
            name='fecha_inicio_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio_factura',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='servicio_factura',
            name='fecha_pedido',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Servicio_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField()),
                ('fecha_inicio_servicio', models.DateTimeField()),
                ('fecha_fin_servicio', models.DateTimeField()),
                ('descripcion_compra_servicio', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='servicio_factura',
            name='servicio_compra_referencia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.servicio_compra'),
        ),
    ]
