# Generated by Django 3.2 on 2023-01-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_produccion_estdo_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision_clie',
            name='estado',
            field=models.CharField(choices=[('No Enviado', 'No Enviado'), ('Enviado', 'Enviado')], default='No Enviado', max_length=100),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='estdo_produccion',
            field=models.CharField(choices=[('No Iniciado', 'No Iniciado'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Saliendo', 'Saliendo')], default='No Iniciado', max_length=100),
        ),
    ]
