# Generated by Django 3.2 on 2023-01-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tipo_trabajador_tipo_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='borrado',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
