# Generated by Django 3.2 on 2023-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_factura_totalfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fechavencimiento',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
