# Generated by Django 3.2 on 2023-01-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230116_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision_clie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura_clie')),
            ],
        ),
        migrations.CreateModel(
            name='Remision_linea_clie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.factura_linea_clie')),
                ('codremision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.remision_clie')),
            ],
        ),
        migrations.DeleteModel(
            name='Albaran_linea_clie',
        ),
    ]
