# Generated by Django 3.2 on 2023-01-17 16:46

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_prov',
            name='imagen_factura_compra',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_path2),
        ),
    ]
