# Generated by Django 3.2 on 2023-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230120_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_compra',
            name='fecha_fin_servicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicio_compra',
            name='fecha_inicio_servicio',
            field=models.DateField(),
        ),
    ]
