# Generated by Django 3.2 on 2023-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_0002_auto_20230118_1434_0003_auto_20230118_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja_diaria',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='monto_total_final',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='monto_total_inicial',
            field=models.FloatField(default=0, null=True),
        ),
    ]
