# Generated by Django 3.2 on 2023-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_remision_clie_fecha_remision'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision_clie',
            name='contador',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
