# Generated by Django 3.2 on 2023-01-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230124_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibir_orden_servicio',
            name='servicio_compra_referencia',
        ),
        migrations.AddField(
            model_name='recibir_orden_servicio',
            name='orden_compra_referencia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orden_compra_servicio'),
        ),
    ]
