# Generated by Django 3.2 on 2023-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_factura_clie_estadoprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha_fin',
            field=models.DateField(),
        ),
    ]
