# Generated by Django 3.2 on 2023-01-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230119_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja_diaria',
            name='neto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja_diaria',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
