# Generated by Django 3.2 on 2023-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_produccion_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_clie',
            name='cantprod',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
