# Generated by Django 3.2 on 2023-01-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remision_clie_contador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision_clie',
            name='contador',
        ),
    ]
