# Generated by Django 3.2 on 2023-01-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_factura_clie_cantprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura_clie',
            name='cantprod',
        ),
    ]
